#!/usr/bin/env node

require('./lib/ext');

var cluster = require('cluster');

var config = require('../config.json');

// ====================================

function init_master() {
    cluster.broadcast = msg => {
        for (let i in cluster.workers) {
            cluster.workers[i].send(msg);
        }
    }

    // reload
    process.on('SIGHUP', () => {
        cluster.broadcast({ op: 'reload' });
        console.log("reloaded");
    });
}

async function init_worker() {
    let dbpool = require('./lib/dbpool');
    let glog = require('./models/glog');

    await dbpool.init([
        ["stats", config.common.db_stats, 1],
    ]);

    await glog.init();

    let server = require('./server');
    let app = require('./app');

    server.run(app, config.reporter.port);
}

// ====================================

(async () => {
    if (cluster.isMaster) {
        // init master
        init_master();

        // fork workers
        for (let i = 0; i < config.reporter.threads; i++) {
            cluster.fork();
        }
    } else {
        // init worker
        await init_worker();
    }
})().catch(console.error);
