package gamedata

var confs_manual = []IConf{
	ConfDropGrpM,
	ConfLimitM,
	ConfMailM,
	ConfNameM,
	ConfDrawOddsM,
	ConfHeroChangeOddsM,
	ConfAppointM,
	ConfShopItemM,
	ConfMarvelRollOddsM,
	ConfActivityM,
	ConfActRushLocalM,
	ConfActRushLocalRewardM,
	ConfActBillLtDayM,
	ConfActMagicSummonOddsM,
	ConfActMonopolyBattleM,
	ConfActMonopolyBoxM,
	ConfActMonopolyHeroM,
	ConfActMonopolyLevelM,
	ConfActMonopolyProblemM,
	ConfActMonopolyShopM,
	ConfActMonopolyTaskM,
	ConfWorldLevelM,
	ConfTowerM,
	ConfActSumonOddsM,
	ConfActMazeRankM,
	ConfActMazeEventMonsterM,
}
